### PR TITLE
Aperture2.0

### PR DESCRIPTION
**Pull request by Jordan-Dennis**
What's new in the `Aperture2.0` branch:
 - This branch has boolean parameters for `occulting` and `softening` allowing the behaviour of the branches to be set more precisely. 
 - The `Spiders` have improved speed and are now an extension of the `Aperture` class. The catch was that currently only even numbers of structs are supported. This is not a problem for `Hubble` but it will need to be fixed for the `JWST` models. 
  - The `HexagonalAperture` and `PolygonalAperture` have been moved back into the `dev` folder because I did not have time to update them onto the new structure. 
This pull request is not to main because documentation is missing. I am asking for review before I document to save time unless we want to change things again.

Regards

Jordan

### CODE REVIEW

**Review by benjaminpope — CHANGES_REQUESTED** [review]
Review!

Skim of the code - looks pretty legit by eye except where noted below, key is testing things.

- [x] All checks have failed - need to make this work with all the unit tests. Issue is the namespace when you import:
```python
_____________________ ERROR collecting tests/wavefronts.py _____________________
tests/wavefronts.py:6: in <module>
    from dLux import Wavefront
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/dLux/__init__.py:19: in <module>
    from .apertures   import *
E   AttributeError: module 'dLux.apertures' has no attribute 'SoftEdgedAperture'
=========================== short test summary info ============================
ERROR tests/wavefronts.py - AttributeError: module 'dLux.apertures' has no at...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
1 error in 2.24s
Error: Process completed with exit code 2.

```
- [x] Would you be able to generate a panel of plots like we did in my office, showing all the components in a typical compound aperture? Doesn't have to be the full thing, but we should visualize it to make sure each component looks correct separately, and then also that they stack together correctly.
- [x] Why are theta and phi both included in the `__init__`? Not sure what phi is doing.
- [x] Personally I get bad vibes using `import matplotlib.pyplot as pyplot` - every other package I've worked with uses `import matplotlib.pyplot as plt`. 
- [x] Instead of `cond` for softening, you could probably do this at `__init__` time by assigning `self.threshold` to be the soft or hard threshold depending on the softening parameter.

Cheers,

Ben

**Review by LouisDesdoigts — COMMENTED** [review]
Yep this basically all looks good, pretty much agree with Ben, except maybe about using using a boolean for softening. If there is distinct behavior for soft and hard-edged then a boolean. If its just setting some continuous values to zero, then we can probably just do that at init time like Ben said.

Overall looks good though 👍

**Comment by Jordan-Dennis** [comment]
The soft and hard edging does not work using a continuous parameter and `equinox` does not let us assign functions in `__init__`. The two metrics are evaluated in a distinctly different way. Is there a particular reason that we want to kill `cond` other than the longer compile times? In this case neither branch is very large so it won't hurt compile time too much.

**Comment by Jordan-Dennis** [comment]
See my above comment. Setting a steepness parameter allowed us to condense the different metrics into a single metric. The documentation is still sparse but that can happen on the `Aperture` branch which this is merging into.

**Comment by benjaminpope** [comment]
Perhaps I said it wrong earlier... I don't mean use a continuous parameter rather than a boolean, I just mean shift the condition to `__init__` time rather than a `cond` at runtime. You could just have 
```python
if self.hard:
    self.threshold = self._soften
else:
    self.threshold = self._hard_threshold
```
etc.

But I don't think this is important...

**Comment by LouisDesdoigts** [comment]
I actually think having it as a boolean makes a lot more sense. When once compiled to XLA there is no overhead for a python boolean branch executing because its not a traced value. Similarly it makes a lot more sense when examining the object to be able to clearly see which object is soft/hard

**Comment by benjaminpope** [comment]
I meant keep it as a boolean, but evaluate the condition at init rather than run time. But I think I have lost this argument.

**Review by benjaminpope — APPROVED** [review]

**Comment by benjaminpope** [comment]
Changes approved, fire away.

**Comment by Jordan-Dennis** [comment]
Thanks for approving. I'm happy to switch back to doing a boolean all I have to do it revert a couple of commits. I misunderstood what you wanted since assigning functions is not possible in `__init__` with `equinox`. Maybe, there is some trick that I do not know, but the following MWE is what I have previously encountered trying to do this with the `Propagators`,
```
>>> class A(equinox.Module):
...     a: float
...     def __init__(self, a):
...             if (a > 0):
...                     self.do = self._do_greater
...             else:
...                     self.do = self._do_lesser
...     def _do_greater(self):
...             print("Do greater")
...     def _do_lesser(self):
...             print("Do lesser")
... 
>>> A(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jordan/anaconda3/envs/dLux/lib/python3.10/site-packages/equinox/module.py", line 131, in __call__
    cls.__init__(self, *args, **kwargs)
  File "<stdin>", line 5, in __init__
  File "/home/jordan/anaconda3/envs/dLux/lib/python3.10/site-packages/equinox/module.py", line 88, in __setattr__
    raise AttributeError(f"Cannot set attribute {name}")
AttributeError: Cannot set attribute do
```

**Comment by Jordan-Dennis** [comment]
Hi guys, 
Not necessarily an issue for this pull request but definitely one that will be required for `Aperture -> main` is how to do global/hierarchical updates to the `CompoundAperture`. For example, what if I want to translate the entire `CompoundAperture` by some amount. Below is how I am currently doing this,
```
def set_offset(self, delta_x_offset: float, delta_y_offset: float):
    for aperture in self.apertures:
        self[aperture] = self[aperture]\
            .set_x_offset(self[aperture].get_x_offset() + delta_x_offset)\
            .set_y_offset(self[aperture].get_y_offset() + delta_y_offset)
    
    return eqx.tree_at(
        lambda aperture: (aperture.x_offset, aperture.y_offset), 
            self, (np.asarray(self.x_offset + delta_x_offset).astype(float), 
                np.asarray(self.y_offset + delta_y_offset).astype(float)))
```
which works fine. This issue then is how to interface this with @LouisDesdoigts new `get_filter_spec` syntax, which I imagine is not using `set_xxxx`. Does anyone have any thoughts?

**Pull request merged**
