### PR TITLE
pixel_fn rewrite within nd_coords

### PR DESCRIPTION
**Pull request by maxecharles**
PR to track progress. See #260

### CODE REVIEW

**Comment by maxecharles** [comment]
@LouisDesdoigts do u still wanna merge it hehe

**Comment by LouisDesdoigts** [comment]
Yah keen for the changes. Although small optimisation, rather than start and end, just calculate the end value as 'k' and linspace from -k, k

**Comment by maxecharles** [comment]
> Yah keen for the changes. Although small optimisation, rather than start and end, just calculate the end value as 'k' and linspace from -k, k

This won't actually work if offset is nonzero as it's not symmetric about zero.

**Comment by LouisDesdoigts** [comment]
Ah yeah of course, this is perfect then. Probs wont merge this till I get some time to actually do some proper work on dLux. This isn't holding up anything youre doing right?

**Comment by maxecharles** [comment]
nup you're all good

**Review by LouisDesdoigts — APPROVED** [review]
Looks good

**Pull request merged**
