### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by benjaminpope**
adding lines 23-24 fixes local install issue #250

### CODE REVIEW

**Comment by benjaminpope** [comment]
@LouisDesdoigts can't do a local install without this?

**Comment by LouisDesdoigts** [comment]
I've not had any issues with local installs without this change... I actually cant replicate that error at all

**Comment by LouisDesdoigts** [comment]
Have you added any folders to your local version?

**Comment by benjaminpope** [comment]
Clashes with the `site`

**Comment by LouisDesdoigts** [comment]
What is `site`? I dont have a `site` folder either locally on anywhere on remote

**Comment by maxecharles** [comment]
have you guys heard of slack

**Comment by benjaminpope** [comment]
fixed, sorry

**Pull request closed without merging**
