### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by Jordan-Dennis**
Fixes according to #81. Note the whole notebooks folder was moved, @LouisDesdoigts is this ok or did you want to copy just the relevant notebooks into `docs/notebooks`?

### CODE REVIEW

**Comment by benjaminpope** [comment]
We don't want to move the whole notebooks folder - we want to create a separate `docs/notebooks/` folder and put only a handful of examples in there, each of them with a clear tutorial and lots of markdown comments explaining things in between cells - like in `ticktack`.

**Review by benjaminpope — CHANGES_REQUESTED** [review]
The `docs/notebooks/basic_usage.ipynb` isn't what we need - this is just the text of the old index page, which I cleaned up yesterday on the main docs.

We just need notebooks that go through some simple examples:

- [ ] making a PSF (could do JWST PSF, building it up in stages like [this nice infographic](https://webbtelescope.org/contents/media/images/01G529MX46J7AFK61GAMSHKSSN) from NASA. 
- [ ] doing phase retrieval (simple example, then with Fresnel, then with flat field - we already have a notebook that does this)
- [ ] designing a Toliman mask (roll the basis creation notebook into the same document as the Toliman mask optimization for a clear flow).

I am happy to write 100% of the markdown text of these pages, but I don't actually have a good handle on the syntax in the latest version of the code. This might actually be a learning experience for me to have to sit down and explain how it works.

**Comment by Jordan-Dennis** [comment]
Sounds good,
I did not realise that my `HexikesExample.ipynb` was on `main` so I had not included it. Unless you were particularly keen on implementing any of those yourself, I can work writing a basic PSF generation for step by step and with Fresnel. I will be doing this today according to the final example in (this)[https://github.com/spacetelescope/poppy/blob/develop/notebooks/Fresnel_Propagation_Demo.ipynb] `poppy` notebook for Hubble where they do both Fraunhofer and Fresnel. I have just been distracted trying to calculate fringe numbers for the MFT version of the Fresnel and then trying to understand the code for the `GaussianLens`.

**Comment by LouisDesdoigts** [comment]
Yep so like you said most of the actual code to do all this is written and in those notebooks, I just haven't had a good opportunity to sit down and put them together into a more smaller set of coherent on-boarding scripts. I agree @benjaminpope that this could actually be a good opportunity to get familiar with it, and you probably have a better understanding of what area need to be focused on for people who aren't familiar with ∂Lux (everything just seems really obvious to me now 😂).

One thing I will say though is that in order to get everything together for the JWST models, we are going to want to add `Source` and `Scene`,  which as discussed in #65 will prompt a structure change in the package. I've been mulling on this more while developing more of the JWST code, and also while talking to people at SPIE about their work and how they might use ∂Lux for their research. Without going into too much detail, I think we want to modularise things more (`Detector` class, `Instrument` class). I think we should have a zoom about this soon to make sure we are all on the same page. This will obviously somewhat affect the way models are constructed and hence the tutorials, but not really in any profound way. I really want to work on this ASAP but am just struggling to find time to actually invest in developing code for longer than 30 minute blocks at the moment... 

Re this PR though - Looks like you're on top of it @benjaminpope?

**Comment by LouisDesdoigts** [comment]
Awesome - All the notebooks work in their present state and cover a most of the core features. Two note though:

1. Some might need a single line changed, in the propagator overhaul `npix_out` became `pixels_out`. Trivial single line fix.
2. Most of the notebooks use 'batched' optical systems to explore/optimise more pupils at the same time. It's a cool flex and useful for the actual pupil design, but actually just a completely unnecessary complexity in terms of any tutorial notebooks, so probably ust strip out the batching stuff and work with a single optical system.

**Comment by Jordan-Dennis** [comment]
Hey guys, sorry for disappearing, the internet has been playing up yesterday and today and it decided to die. I'm still sorting out the lenses but it sounds like this is all going well.

**Comment by benjaminpope** [comment]
No worries - it is not urgent, but basically all we need here is if someone can point me to working code that does everything we need... just worried about how some of the notebooks have survived the changes...

**Comment by benjaminpope** [comment]
Update: have added the phase retrieval and CLIMB phase design examples.

Next on the list:
- [ ] JWST pupil - need @Jordan-Dennis input on fixing these functions up
- [ ] FF detection - can do this solo probably

**Comment by Jordan-Dennis** [comment]
Sorry for disappearing, what needs to happen for this now?

**Comment by benjaminpope** [comment]
This PR is dead, but the same vibe remains - we want to have a tutorial on how to set up a JWST pupil, and how to use the Fresnel code.

**Comment by Jordan-Dennis** [comment]
OK :+1: cool. I will close this PR then, since I have created the relevant issue. (#110)

**Pull request closed without merging**
